# Generated by Django 3.0.5 on 2020-04-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200422_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='vendor',
            field=models.ManyToManyField(blank=True, help_text='Select one or multiple vendor locations', to='products.MfgLoc', verbose_name='Vendor Locations'),
        ),
    ]
